- name: integration of terraform and ansible
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo  
  
  tasks:
  - name: installing httpd
    package:
         name: httpd
         state: present
  - name: installing php
    package:
         name: php
         state: present
  - name: starting httpd service
    service:
         name: httpd
         state: started
  - name: installing git
    package:
         name: git
         state: present
  - name: cloning git repo
    ansible.builtin.git:
            repo: "https://github.com/ishajain140/index_files.git/"
            dest: /var/www/html/web
